### ISSUE TITLE
Version change pop-up

### ISSUE THREAD

**Issue by steima** [variocube/app-ui#25]
## Summary

Interlinked with the help system we should be able to show Change logs.

### Current Behaviour

We send out manual e-mails.

### Desired Behaviour

In the help system we install a dedicated page which reflects the change log for each application.

If a change-log URL is configured on the help context the help context should automatically do the following:

 - If in the `localStorage` there is no versioning information found > show a pop-up with some general info on the change log and write the current version (from NPM) to `localStorage`
 - if the current version in `localStorage` is older than the application version (from NPM) show the pop-up and write the version info to local storage - for the check we use only minor versions up `0.0.X` (for version check use the `semver` package!)
 - In the footer bar support showing a Change-Log link that is only rendere if the change log URL is configured

## Tasks

 - [ ] Task 1
 - [ ] Task 2

**Comment by steima** [comment]
Provide a script or process to automatically put the GH tag name into package.json as version.

**Comment by dhauber** [comment]
@steima PR erstellt, bitte mal kontrollieren, ob die Umsetzung so ok ist.

Die Texte vom Popup sind jetzt noch hardcodiert. Sollen die via props übergeben werden?

**Comment by dhauber** [comment]
The "general info" dialog is not necessary. We only show the dialog when there's a new version.
